  G:\dev\wordpress\groomingfurryangels                                                                                                                                  Size        Type         Last Modified  
   css                                                                                                                                                                    -   directory   2025-02-09 08:02 PM  
   └  output.css                                                                                                                                                   65.94 KB         css   2025-02-09 03:24 PM  
   includes                                                                                                                                                               -   directory   2025-02-09 03:24 PM  
   js                                                                                                                                                                     -   directory   2025-02-09 08:02 PM  
   node_modules                                                                                                                                                           -   directory   2025-02-09 07:48 PM  
   src                                                                                                                                                                    -   directory   2025-02-09 08:02 PM  
   └  Categories.php                                                                                                                                                   130 B         php   2025-02-09 03:24 PM  
   vendor                                                                                                                                                                 -   directory   2025-02-09 03:24 PM  
     composer                                                                                                                                                             -   directory   2025-02-09 03:24 PM  
   └  autoload.php                                                                                                                                                     796 B         php   2025-02-09 03:24 PM  
    archive.php                                                                                                                                                          0 B         php   2025-02-09 03:24 PM  
    composer.json                                                                                                                                            󰄱         76 B        json   2025-02-09 08:04 PM  
    footer.php                                                                                                                                                          41 B         php   2025-02-09 03:24 PM  
    functions.php                                                                                                                                            󰄱        957 B         php   2025-02-09 08:02 PM  
    header.php                                                                                                                                                        3.2 KB         php   2025-02-09 03:50 PM  
    index.php                                                                                                                                                           78 B         php   2025-02-09 03:24 PM  
    package-lock.json                                                                                                                                        󰄱     47.16 KB        json   2025-02-09 07:48 PM  
    package.json                                                                                                                                             󰄱        463 B        json   2025-02-09 08:02 PM  
    page.php                                                                                                                                                            80 B         php   2025-02-09 03:24 PM  
    single.php                                                                                                                                                         159 B         php   2025-02-09 03:24 PM  
    style.css                                                                                                                                                          182 B         css   2025-02-09 03:24 PM  
   (2 hidden items)
